title: Sustainability as a Service Lab Notebook
url: https://susaas.kemitchell.com
homepage: https://susaas.kemitchell.com
repository: kemitchell/susaas.kemitchell.com
repository_url: "https://github.com/kemitchell/susaas.kemitchell.com"
plugins:
  - jekyll-feed
feed:
  collections:
    - projects
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - Makefile
collections:
  projects:
    output: true
