title: Open Funding Lab Notebook
url: https://lab.kemitchell.com
homepage: https://lab.kemitchell.com
repository: kemitchell/lab.kemitchell.com
repository_url: "https://github.com/kemitchell/lab.kemitchell.com"
plugins:
  - jekyll-feed
feed:
  collections:
    - projects
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - Makefile
collections:
  projects:
    output: true
